#define NSUDO_VERSION_TOSTRING_2(arg) #arg
#define NSUDO_VERSION_TOSTRING(arg) NSUDO_VERSION_TOSTRING_2(arg)
#define NSUDO_VERSION_STRING \
	NSUDO_VERSION_TOSTRING(NSUDO_VERSION_MAJOR) \
	"." \
	NSUDO_VERSION_TOSTRING(NSUDO_VERSION_MINOR) \
	"." \
	NSUDO_VERSION_TOSTRING(NSUDO_VERSION_BUILD) \
	"." \
	NSUDO_VERSION_TOSTRING(NSUDO_VERSION_REVISION)
